Fix call to private method on old Rubies (#1067)
Was causing:

    NoMethodError: private method `include' called for
      ActionDispatch::Request:Class